### ISSUE TITLE
h5bench_write does not close the dataset correctly

### ISSUE THREAD

**Issue by yzanhua** [hpc-io/h5bench#40] opened 2022-02-07 19:46 UTC
**Bug Report**

The write benchmark does not close the dataset correctly using configuration `"MEM_PATTERN": "CONTIG"` and `"FILE_PATTERN": "INTERLEAVED"`.
```shell
$ cat full-test/a7311c05/stderr
HDF5-DIAG: Error detected in HDF5 (1.13.0) MPI-process 1:
  #000: H5D.c line 504 in H5Dclose_async(): not a dataset ID
    major: Invalid arguments to routine
    minor: Inappropriate type
...
```

**To Reproduce**

How are you building/running h5bench?

```bash
h5bench --debug configuration.json
```

What is the input configuration file you use?

```json
{
    "mpi": {
        "command": "mpirun",
        "ranks": "2"
    },
    "vol": {
    },
    "file-system": {
    },
    "directory": "full-test",
    "benchmarks": [
        {
            "benchmark": "write",
            "file": "test.h5",
            "configuration": {
                "MEM_PATTERN": "CONTIG",
                "FILE_PATTERN": "INTERLEAVED",
                "NUM_PARTICLES": "1 M",
                "TIMESTEPS": "5",
                "DELAYED_CLOSE_TIMESTEPS": "2",
                "COLLECTIVE_DATA": "NO",
                "COLLECTIVE_METADATA": "YES",
                "EMULATED_COMPUTE_TIME_PER_TIMESTEP": "1 s", 
                "NUM_DIMS": "1",
                "DIM_1": "16777216",
                "DIM_2": "1",
                "DIM_3": "1",
                "CSV_FILE": "output.csv",
                "MODE": "SYNC"
            }
        }
    ]
}
```

**Expected Behavior**

No error should be reported in stderr.

**Software Environment**

 - version of h5bench: main branch
 - installed h5bench using: from source
 - operating system: Red Hat Enterprise Linux 8.5 (Ootpa)
 - machine: private machine
 - version of HDF5: 1.13.0
 - version of VOL-ASYNC: not installed
 - name and version of MPI: MPICH 3.4.2 [link here](https://www.mpich.org/downloads/)

**Comment by jeanbez** [comment] 2022-02-15 16:40
@yzanhua we could not reproduce the error you reported. We have also included additional tests in our CI to cover this, but they did not report any errors. Could you try building HDF5 and h5bench again to ensure it was not some other build issue?

**Comment by jeanbez** [comment] 2022-03-08 17:28
@yzanhua We could not reproduce the issues and have included new tests in our CI to cover this. Are you still facing this issue? If everything was solved, please let us know, otherwise, we will be closing the issue on March 10.

**Comment by jeanbez** [comment] 2022-03-11 17:53
We believe this issue has been resolved and since we have not heard back, we are closing it.

**Closed by jeanbez** 2022-03-11 17:53 UTC
Labels: bug
